### ISSUE TITLE
Create Tab Bar in React Native CLI

### ISSUE THREAD

**Issue by rahulvermafreelancer** [rahulvermafreelancer/cityclub#1]
Hi Everyone,
We are presenting a new application for booking system for multiple areas. In which we need to create the Tab bar that is present in the Figma design. If you are familiar with React Native CLI then you can start contributing in the repo.

https://www.figma.com/design/VaGVvxtoxSQIYwBAhCNRbI/MBooking---Movie-ticket-booking-app-(Community)?node-id=87-11&t=Dmcubtv8gFFJAgxA-1

Please refer the link for design

**Comment by HarshitPachori** [comment]
Assign me this issue I will implement tab bar in this application

**Comment by rahulvermafreelancer** [comment]
Hi @HarshitPachori, Sure i will assign this issue to you. Please create a new branch before making any changes.
Thanks

**Comment by rahulvermafreelancer** [comment]
The Tab Bar is now working properly and We made the changes as they did in the PR.

**Comment by HarshitPachori** [comment]
Hey @rahulvermafreelancer , Could you please add hacktoberfest-accepted label to this ?
